### ISSUE TITLE
Prune crashes attempting to delete 404 groups

### ISSUE THREAD

**Issue by staze** [BIG-RAT/Prune#23]
Importing saved json, hitting delete results in a crash. Crash log forthcoming.

**Comment by jshirle2** [comment]
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Prune [43685]
Path:                  /Applications/Prune.app/Contents/MacOS/Prune
Identifier:            com.jamf.pse.prune
Version:               2.2.4 (1)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               505

Date/Time:             2022-07-22 15:21:01.0997 -0700
OS Version:            macOS 12.4 (21F79)
Report Version:        12
Anonymous UUID:        146DE987-9D36-0E22-CD59-D9F9DA5BE738


Time Awake Since Boot: 190000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x000000010298bd50
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [43685]

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   Prune                         	       0x10298bd50 0x102958000 + 212304
1   Prune                         	       0x102988894 0x102958000 + 198804
2   Prune                         	       0x10298efc4 0x102958000 + 225220
3   AppKit                        	       0x19e361844 -[NSApplication(NSResponder) sendAction:to:from:] + 460
4   AppKit                        	       0x19e361640 -[NSControl sendAction:to:] + 96
5   AppKit                        	       0x19e361548 __26-[NSCell _sendActionFrom:]_block_invoke + 152
6   AppKit                        	       0x19e36143c -[NSCell _sendActionFrom:] + 204
7   AppKit                        	       0x19e361360 -[NSButtonCell _sendActionFrom:] + 104
8   AppKit                        	       0x19e35e1ac NSControlTrackMouse + 1752
9   AppKit                        	       0x19e35daa8 -[NSCell trackMouse:inRect:ofView:untilMouseUp:] + 160
10  AppKit                        	       0x19e35d91c -[NSButtonCell trackMouse:inRect:ofView:untilMouseUp:] + 740
11  AppKit                        	       0x19e35cb8c -[NSControl mouseDown:] + 632
12  AppKit                        	       0x19e35affc -[NSWindow(NSEventRouting) _handleMouseDownEvent:isDelayedEvent:] + 4528
13  AppKit                        	       0x19e2ce374 -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 2444
14  AppKit                        	       0x19e2cd780 -[NSWindow(NSEventRouting) sendEvent:] + 348
15  AppKit                        	       0x19e2cc728 -[NSApplication(NSEvent) sendEvent:] + 2780
16  AppKit                        	       0x19e5864f8 -[NSApplication _handleEvent:] + 76
17  AppKit                        	       0x19e14e278 -[NSApplication run] + 636
18  AppKit                        	       0x19e11f96c NSApplicationMain + 1132
19  Prune                         	       0x10295b2e4 0x102958000 + 13028
20  dyld                          	       0x102c4108c start + 520

Thread 1::  Dispatch queue: com.jamfpse.token_refreshQ
0   libsystem_kernel.dylib        	       0x19b4f206c __semwait_signal + 8
1   libsystem_c.dylib             	       0x19b3fafc8 nanosleep + 220
2   libsystem_c.dylib             	       0x19b405b78 sleep + 52
3   Prune                         	       0x1029a0aa0 0x102958000 + 297632
4   Prune                         	       0x10299e64c 0x102958000 + 288332
5   libdispatch.dylib             	       0x19b3665f0 _dispatch_call_block_and_release + 32
6   libdispatch.dylib             	       0x19b3681b4 _dispatch_client_callout + 20
7   libdispatch.dylib             	       0x19b36f8a8 _dispatch_lane_serial_drain + 668
8   libdispatch.dylib             	       0x19b370404 _dispatch_lane_invoke + 392
9   libdispatch.dylib             	       0x19b37ac98 _dispatch_workloop_worker_thread + 648
10  libsystem_pthread.dylib       	       0x19b528360 _pthread_wqthread + 288
11  libsystem_pthread.dylib       	       0x19b527080 start_wqthread + 8

Thread 2:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	       0x19b4ee8b0 mach_msg_trap + 8
1   libsystem_kernel.dylib        	       0x19b4eed20 mach_msg + 76
2   CoreFoundation                	       0x19b5f92b0 __CFRunLoopServiceMachPort + 372
3   CoreFoundation                	       0x19b5f7760 __CFRunLoopRun + 1180
4   CoreFoundation                	       0x19b5f6b24 CFRunLoopRunSpecific + 600
5   AppKit                        	       0x19e2ca374 _NSEventThread + 196
6   libsystem_pthread.dylib       	       0x19b52c26c _pthread_start + 148
7   libsystem_pthread.dylib       	       0x19b52708c thread_start + 8

Thread 3:
0   libsystem_pthread.dylib       	       0x19b527078 start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	       0x19b527078 start_wqthread + 0

Thread 5:
0   libsystem_pthread.dylib       	       0x19b527078 start_wqthread + 0

Thread 6:
0   libsystem_pthread.dylib       	       0x19b527078 start_wqthread + 0

Thread 7:
0   libsystem_pthread.dylib       	       0x19b527078 start_wqthread + 0

Thread 8:
0   libsystem_pthread.dylib       	       0x19b527078 start_wqthread + 0

Thread 9:
0   libsystem_pthread.dylib       	       0x19b527078 start_wqthread + 0

Thread 10:
0   libsystem_pthread.dylib       	       0x19b527078 start_wqthread + 0

Thread 11:
0   libsystem_pthread.dylib       	       0x19b527078 start_wqthread + 0


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x00000001a8a20ebc   x2: 0x8c7847ca61e8fd33   x3: 0x0800000000000000
    x4: 0x0800000000000000   x5: 0x0000000000000004   x6: 0x000000000000006c   x7: 0x0000000000000000
    x8: 0x000060000086c108   x9: 0x0000000400000003  x10: 0xfffffffe00000000  x11: 0x0000000400000003
   x12: 0x0000000200000003  x13: 0x0800000000000000  x14: 0x000000016d4a6588  x15: 0x3f83442c8cdc21ce
   x16: 0x00000001a8a5f63c  x17: 0x00000001a87c8c00  x18: 0x0000000000000000  x19: 0x000000016d4a6670
   x20: 0x000060000086c100  x21: 0x0000000000000001  x22: 0x0000000134b0c2c0  x23: 0xe300000000000000
   x24: 0x00000000006c6c41  x25: 0x0000000000000012  x26: 0x5000600002655200  x27: 0x0000000134b0c2c0
   x28: 0x0000000134b0c488   fp: 0x000000016d4a6a30   lr: 0x0000000102988894
    sp: 0x000000016d4a6660   pc: 0x000000010298bd50 cpsr: 0x60001000
   far: 0x0000000102988204  esr: 0xf2000001 (Breakpoint) brk 1

Binary Images:
       0x102958000 -        0x1029affff com.jamf.pse.prune (2.2.4) <8989ed7a-8ec7-3b9e-80fe-eea0f909a826> /Applications/Prune.app/Contents/MacOS/Prune
       0x19e11c000 -        0x19efd3fff com.apple.AppKit (6.9) <a773dd23-b1c8-3c9b-9175-9a71d210ace0> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
       0x102c3c000 -        0x102c9bfff dyld (*) <d9c2a46e-8dc4-3950-9d6a-f799e8ccb683> /usr/lib/dyld
       0x19b4ed000 -        0x19b524fff libsystem_kernel.dylib (*) <03f48dc5-caa7-3678-af61-1a3c7fa8b06e> /usr/lib/system/libsystem_kernel.dylib
       0x19b3ec000 -        0x19b46dfff libsystem_c.dylib (*) <86746b94-88e3-342d-b2b2-54303404e492> /usr/lib/system/libsystem_c.dylib
       0x19b364000 -        0x19b3aafff libdispatch.dylib (*) <f9300d47-d3db-3349-8a6d-acb68cd9983b> /usr/lib/system/libdispatch.dylib
       0x19b525000 -        0x19b531fff libsystem_pthread.dylib (*) <42166a2c-89a9-3c38-a215-f028544cea23> /usr/lib/system/libsystem_pthread.dylib
       0x19b574000 -        0x19babafff com.apple.CoreFoundation (6.9) <994db908-11a1-3e43-b7df-25c09d51368a> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.0G resident=0K(0%) swapped_out_or_unallocated=1.0G(100%)
Writable regions: Total=1.6G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.6G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               384K        3 
Activity Tracing                   256K        1 
CG backing stores                  768K        4 
CG image                           672K       39 
ColorSync                          544K       27 
CoreAnimation                     2272K       75 
CoreGraphics                        32K        2 
CoreServices                      1024K        4 
CoreUI image data                 1760K       24 
Foundation                          48K        2 
Kernel Alloc Once                   32K        1 
MALLOC                           288.6M       67 
MALLOC guard page                  384K       19 
MALLOC_MEDIUM (reserved)         960.0M        8         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
SQLite page cache                   64K        1 
STACK GUARD                       56.2M       12 
Stack                             13.8M       12 
VM_ALLOCATE                        192K       12 
__AUTH                            2494K      294 
__AUTH_CONST                      19.4M      486 
__CTF                               756        1 
__DATA                            14.8M      477 
__DATA_CONST                      17.5M      495 
__DATA_DIRTY                      1725K      205 
__FONT_DATA                          4K        1 
__LINKEDIT                       577.7M        8 
__OBJC_CONST                      3358K      264 
__OBJC_RO                         83.0M        1 
__OBJC_RW                         3152K        1 
__TEXT                           480.5M      513 
__UNICODE                          592K        1 
dyld private memory               1024K        1 
libnetwork                         640K       16 
mapped file                      186.0M       49 
shared memory                      928K       18 
===========                     =======  ======= 
TOTAL                              3.0G     3145 
TOTAL, minus reserved VM space     1.7G     3145 



-----------
Full Report
-----------

{"app_name":"Prune","timestamp":"2022-07-22 15:21:03.00 -0700","app_version":"2.2.4","slice_uuid":"8989ed7a-8ec7-3b9e-80fe-eea0f909a826","build_version":"1","platform":1,"bundleID":"com.jamf.pse.prune","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.4 (21F79)","incident_id":"54ADC99B-1544-49D1-8FD4-CDA89E5E02AE","name":"Prune"}
{
  "uptime" : 190000,
  "procLaunch" : "2022-07-22 15:16:26.9323 -0700",
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 505,
  "deployVersion" : 210,
  "modelCode" : "iMac21,1",
  "procStartAbsTime" : 4666373680973,
  "coalitionID" : 5966,
  "osVersion" : {
    "train" : "macOS 12.4",
    "build" : "21F79",
    "releaseType" : "User"
  },
  "captureTime" : "2022-07-22 15:21:01.0997 -0700",
  "incident" : "54ADC99B-1544-49D1-8FD4-CDA89E5E02AE",
  "bug_type" : "309",
  "pid" : 43685,
  "procExitAbsTime" : 4672952935648,
  "translated" : false,
  "cpuType" : "ARM-64",
  "procName" : "Prune",
  "procPath" : "\/Applications\/Prune.app\/Contents\/MacOS\/Prune",
  "bundleInfo" : {"CFBundleShortVersionString":"2.2.4","CFBundleVersion":"1","CFBundleIdentifier":"com.jamf.pse.prune"},
  "storeInfo" : {"deviceIdentifierForVendor":"74BB1B82-D0CD-5B1A-B666-E1F66CAB556D","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.jamf.pse.prune",
  "crashReporterKey" : "146DE987-9D36-0E22-CD59-D9F9DA5BE738",
  "sip" : "enabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000001, 0x000000010298bd50","rawCodes":[1,4338531664],"type":"EXC_BREAKPOINT","signal":"SIGTRAP"},
  "termination" : {"flags":0,"code":5,"namespace":"SIGNAL","indicator":"Trace\/BPT trap: 5","byProc":"exc handler","byPid":43685},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":880562,"threadState":{"x":[{"value":0},{"value":7124160188,"symbolLocation":0,"symbol":"_swift_release_"},{"value":10121919097066814771},{"value":576460752303423488},{"value":576460752303423488},{"value":4},{"value":108},{"value":0},{"value":105553125097736},{"value":17179869187},{"value":18446744065119617024},{"value":17179869187},{"value":8589934595},{"value":576460752303423488},{"value":6128559496},{"value":4576576604471042510},{"value":7124416060,"symbolLocation":0,"symbol":"swift_bridgeObjectRelease"},{"value":7121701888,"symbolLocation":560,"symbol":"Hasher.combine(bytes:)"},{"value":0},{"value":6128559728},{"value":105553125097728},{"value":1},{"value":5178966720},{"value":16357073846609641472},{"value":7105601},{"value":18},{"value":5764713076190695936},{"value":5178966720},{"value":5178967176}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4338518164},"cpsr":{"value":1610616832},"fp":{"value":6128560688},"sp":{"value":6128559712},"esr":{"value":4060086273,"description":"(Breakpoint) brk 1"},"pc":{"value":4338531664,"matchesCrashFrame":1},"far":{"value":4338516484}},"queue":"com.apple.main-thread","frames":[{"imageOffset":212304,"imageIndex":0},{"imageOffset":198804,"imageIndex":0},{"imageOffset":225220,"imageIndex":0},{"imageOffset":2381892,"symbol":"-[NSApplication(NSResponder) sendAction:to:from:]","symbolLocation":460,"imageIndex":1},{"imageOffset":2381376,"symbol":"-[NSControl sendAction:to:]","symbolLocation":96,"imageIndex":1},{"imageOffset":2381128,"symbol":"__26-[NSCell _sendActionFrom:]_block_invoke","symbolLocation":152,"imageIndex":1},{"imageOffset":2380860,"symbol":"-[NSCell _sendActionFrom:]","symbolLocation":204,"imageIndex":1},{"imageOffset":2380640,"symbol":"-[NSButtonCell _sendActionFrom:]","symbolLocation":104,"imageIndex":1},{"imageOffset":2367916,"symbol":"NSControlTrackMouse","symbolLocation":1752,"imageIndex":1},{"imageOffset":2366120,"symbol":"-[NSCell trackMouse:inRect:ofView:untilMouseUp:]","symbolLocation":160,"imageIndex":1},{"imageOffset":2365724,"symbol":"-[NSButtonCell trackMouse:inRect:ofView:untilMouseUp:]","symbolLocation":740,"imageIndex":1},{"imageOffset":2362252,"symbol":"-[NSControl mouseDown:]","symbolLocation":632,"imageIndex":1},{"imageOffset":2355196,"symbol":"-[NSWindow(NSEventRouting) _handleMouseDownEvent:isDelayedEvent:]","symbolLocation":4528,"imageIndex":1},{"imageOffset":1778548,"symbol":"-[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:]","symbolLocation":2444,"imageIndex":1},{"imageOffset":1775488,"symbol":"-[NSWindow(NSEventRouting) sendEvent:]","symbolLocation":348,"imageIndex":1},{"imageOffset":1771304,"symbol":"-[NSApplication(NSEvent) sendEvent:]","symbolLocation":2780,"imageIndex":1},{"imageOffset":4629752,"symbol":"-[NSApplication _handleEvent:]","symbolLocation":76,"imageIndex":1},{"imageOffset":205432,"symbol":"-[NSApplication run]","symbolLocation":636,"imageIndex":1},{"imageOffset":14700,"symbol":"NSApplicationMain","symbolLocation":1132,"imageIndex":1},{"imageOffset":13028,"imageIndex":0},{"imageOffset":20620,"symbol":"start","symbolLocation":520,"imageIndex":2}]},{"id":880794,"queue":"com.jamfpse.token_refreshQ","frames":[{"imageOffset":20588,"symbol":"__semwait_signal","symbolLocation":8,"imageIndex":3},{"imageOffset":61384,"symbol":"nanosleep","symbolLocation":220,"imageIndex":4},{"imageOffset":105336,"symbol":"sleep","symbolLocation":52,"imageIndex":4},{"imageOffset":297632,"imageIndex":0},{"imageOffset":288332,"imageIndex":0},{"imageOffset":9712,"symbol":"_dispatch_call_block_and_release","symbolLocation":32,"imageIndex":5},{"imageOffset":16820,"symbol":"_dispatch_client_callout","symbolLocation":20,"imageIndex":5},{"imageOffset":47272,"symbol":"_dispatch_lane_serial_drain","symbolLocation":668,"imageIndex":5},{"imageOffset":50180,"symbol":"_dispatch_lane_invoke","symbolLocation":392,"imageIndex":5},{"imageOffset":93336,"symbol":"_dispatch_workloop_worker_thread","symbolLocation":648,"imageIndex":5},{"imageOffset":13152,"symbol":"_pthread_wqthread","symbolLocation":288,"imageIndex":6},{"imageOffset":8320,"symbol":"start_wqthread","symbolLocation":8,"imageIndex":6}]},{"id":880835,"name":"com.apple.NSEventThread","frames":[{"imageOffset":6320,"symbol":"mach_msg_trap","symbolLocation":8,"imageIndex":3},{"imageOffset":7456,"symbol":"mach_msg","symbolLocation":76,"imageIndex":3},{"imageOffset":545456,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":372,"imageIndex":7},{"imageOffset":538464,"symbol":"__CFRunLoopRun","symbolLocation":1180,"imageIndex":7},{"imageOffset":535332,"symbol":"CFRunLoopRunSpecific","symbolLocation":600,"imageIndex":7},{"imageOffset":1762164,"symbol":"_NSEventThread","symbolLocation":196,"imageIndex":1},{"imageOffset":29292,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":6},{"imageOffset":8332,"symbol":"thread_start","symbolLocation":8,"imageIndex":6}]},{"id":884951,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":6}]},{"id":884952,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":6}]},{"id":885106,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":6}]},{"id":885108,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":6}]},{"id":885227,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":6}]},{"id":885228,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":6}]},{"id":885229,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":6}]},{"id":885230,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":6}]},{"id":885231,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":6}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4338319360,
    "CFBundleShortVersionString" : "2.2.4",
    "CFBundleIdentifier" : "com.jamf.pse.prune",
    "size" : 360448,
    "uuid" : "8989ed7a-8ec7-3b9e-80fe-eea0f909a826",
    "path" : "\/Applications\/Prune.app\/Contents\/MacOS\/Prune",
    "name" : "Prune",
    "CFBundleVersion" : "1"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6946930688,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 15433728,
    "uuid" : "a773dd23-b1c8-3c9b-9175-9a71d210ace0",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2113.50.132"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4341350400,
    "size" : 393216,
    "uuid" : "d9c2a46e-8dc4-3950-9d6a-f799e8ccb683",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6900600832,
    "size" : 229376,
    "uuid" : "03f48dc5-caa7-3678-af61-1a3c7fa8b06e",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6899548160,
    "size" : 532480,
    "uuid" : "86746b94-88e3-342d-b2b2-54303404e492",
    "path" : "\/usr\/lib\/system\/libsystem_c.dylib",
    "name" : "libsystem_c.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6898991104,
    "size" : 290816,
    "uuid" : "f9300d47-d3db-3349-8a6d-acb68cd9983b",
    "path" : "\/usr\/lib\/system\/libdispatch.dylib",
    "name" : "libdispatch.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6900830208,
    "size" : 53248,
    "uuid" : "42166a2c-89a9-3c38-a215-f028544cea23",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6901153792,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5533696,
    "uuid" : "994db908-11a1-3e43-b7df-25c09d51368a",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "1863"
  }
],
  "sharedCache" : {
  "base" : 6897532928,
  "size" : 3136077824,
  "uuid" : "513553bb-5ca5-3b9e-a613-b0603ffe3038"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.0G resident=0K(0%) swapped_out_or_unallocated=1.0G(100%)\nWritable regions: Total=1.6G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.6G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               384K        3 \nActivity Tracing                   256K        1 \nCG backing stores                  768K        4 \nCG image                           672K       39 \nColorSync                          544K       27 \nCoreAnimation                     2272K       75 \nCoreGraphics                        32K        2 \nCoreServices                      1024K        4 \nCoreUI image data                 1760K       24 \nFoundation                          48K        2 \nKernel Alloc Once                   32K        1 \nMALLOC                           288.6M       67 \nMALLOC guard page                  384K       19 \nMALLOC_MEDIUM (reserved)         960.0M        8         reserved VM address space (unallocated)\nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nSQLite page cache                   64K        1 \nSTACK GUARD                       56.2M       12 \nStack                             13.8M       12 \nVM_ALLOCATE                        192K       12 \n__AUTH                            2494K      294 \n__AUTH_CONST                      19.4M      486 \n__CTF                               756        1 \n__DATA                            14.8M      477 \n__DATA_CONST                      17.5M      495 \n__DATA_DIRTY                      1725K      205 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       577.7M        8 \n__OBJC_CONST                      3358K      264 \n__OBJC_RO                         83.0M        1 \n__OBJC_RW                         3152K        1 \n__TEXT                           480.5M      513 \n__UNICODE                          592K        1 \ndyld private memory               1024K        1 \nlibnetwork                         640K       16 \nmapped file                      186.0M       49 \nshared memory                      928K       18 \n===========                     =======  ======= \nTOTAL                              3.0G     3145 \nTOTAL, minus reserved VM space     1.7G     3145 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "6112e14f37f5d11121dcd519",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "62d569e10c13797292a8c118"
      },
      "deploymentId" : 240000186
    },
    {
      "rolloutId" : "5ffde50ce2aacd000d47a95f",
      "factorPackIds" : {

      },
      "deploymentId" : 240000171
    }
  ],
  "experiments" : [

  ]
}
}

Model: iMac21,1, BootROM 7459.121.3, proc 8:4:4 processors, 8 GB, SMC 
Graphics: Apple M1, Apple M1, Built-In
Display: Raritan CIM, 1920 x 1080 (1080p FHD - Full High Definition), Main, MirrorOn, Online
Display: iMac, Retina 4.5K (4480 x 2520), MirrorOn, Online
Memory Module: LPDDR4
AirPort: Wi-Fi, wl0: Mar 23 2022 19:44:05 version 18.60.27.0.7.8.129 FWID 01-62606619
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Ethernet, Ethernet, en0
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: D2CIM-VUSB
USB Device: USB31Bus
USB Device: Magic Keyboard with Touch ID
Thunderbolt Bus: iMac, Apple Inc.
Thunderbolt Bus: iMac, Apple Inc.

**Comment by BIG-RAT** [comment]
Thanks for the heads up.  Should be resolved with the latest build, v2.2.5.
